---
- name: Check DH file
  stat:
    path: /etc/ssl/certs/dhparam.pem
  register: stat_result

- name: Create file with DH params
  command:
    cmd: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  when: not stat_result.stat.exists

- name: Copy config file
  template:
    src: https.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: restart nginx
