---
- name: Create DB for wordpress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    collation: "utf8_unicode_ci"
    encoding: "utf8"

- name: Create user for wordpress db and grant him access ALL
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: 'wordpress.*:ALL,GRANT'

- name: Create user for wordpress db and grant him access SELECT
  mysql_user:
    name: "{{ wp_db_read_user }}"
    password: "{{ wp_db_read_user_password }}"
    priv: 'wordpress.*:SELECT,GRANT'

- name: Install additional php extensions and unzip
  yum:
    name:
      - php-curl
      - php-gd
      - php-intl
      - php-mbstring
      - php-soap
      - php-xml
      - php-xmlrpc
      - php-zip
      - unzip
    state: present
  notify: restart php-fpm

- name: Copy Nginx main config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: restart nginx

- name: Copy Nginx config file
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: restart nginx

- name: Download Wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /usr/share/nginx/html/
    remote_src: true
    owner: nginx
    group: nginx


- name: Fetch random salts for wp-config.php
  delegate_to: localhost
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: true
  become: false
  register: 'wp_salt_array'

- name: Set wp_salt fact
  set_fact:
    wp_salt: '{{ wp_salt_array.content }}'

- name: Copy Wordpress config file
  template:
    src: wp-config.php.j2
    dest: /usr/share/nginx/html/wordpress/wp-config.php
    owner: nginx
    group: nginx
    mode: 0600

- name: Check slow-query.log for MariaDB
  stat:
    path: /var/log/mariadb/slow-query.log
  register: stat_result

- name: Create slow-query.log for MariaDB
  file:
    path: /var/log/mariadb/slow-query.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0644
  when: not stat_result.stat.exists

- name: Copy MariaDB config file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    mode: 0644
  notify:
    - Stop MariaDB
    - Wait until the socket file is removed
    - Find InnoDB log files
    - Remove default InnoDB log files
    - Start MariaDB
